// <auto-generated />
using System;
using Eskon.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eskon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228223652_test0001")]
    partial class test0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eskon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId");

                    b.HasIndex("AmenityName")
                        .IsUnique()
                        .HasDatabaseName("IX_Amenity_Name");

                    b.HasIndex("Category", "AmenityName")
                        .HasDatabaseName("IX_Amenity_Category_Name");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            AmenityName = "WiFi",
                            Category = "General"
                        },
                        new
                        {
                            AmenityId = 2,
                            AmenityName = "Air Conditioning",
                            Category = "Climate"
                        },
                        new
                        {
                            AmenityId = 3,
                            AmenityName = "Swimming Pool",
                            Category = "Luxury"
                        },
                        new
                        {
                            AmenityId = 4,
                            AmenityName = "Gym",
                            Category = "Luxury"
                        },
                        new
                        {
                            AmenityId = 5,
                            AmenityName = "Parking",
                            Category = "General"
                        });
                });

            modelBuilder.Entity("Eskon.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "92b75286-d8f8-4061-9995-e6e23ccdee94",
                            ConcurrencyStamp = "f51e5a91-bced-49c2-8b86-c2e170c0846c",
                            IsDefault = false,
                            IsDisabled = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9eaa03df-8e4f-4161-85de-0f6e5e30bfd4",
                            ConcurrencyStamp = "5ee6bc12-5cb0-4304-91e7-6a00744e042a",
                            IsDefault = true,
                            IsDisabled = false,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Eskon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99d2bbc6-bc54-4248-a172-a77de3ae4430",
                            Email = "admin@Eskon.com",
                            EmailConfirmed = true,
                            FirstName = "Eskon",
                            IsDisabled = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ESKON.COM",
                            NormalizedUserName = "ADMIN@ESKON.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIW3NlZn9JYsa1r4A98wfj4CNoSIfdtdMYb7T3JlYn3ZZenM6GeinhFZqJVYCcTQ7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55BF92C9EF0249CDA210D85D1A851BC9",
                            TwoFactorEnabled = false,
                            UserName = "admin@Eskon.com"
                        });
                });

            modelBuilder.Entity("Eskon.Domain.Entities.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseId"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("HouseId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PricePerMonth");

                    b.HasIndex("LocationId", "PricePerMonth");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            Area = 120.0,
                            CreatedAt = new DateTime(2025, 10, 1, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "A spacious and modern apartment located in the heart of Cairo.",
                            LocationId = 1,
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 7500m,
                            RatingCount = 0,
                            Title = "Modern Apartment in Downtown"
                        },
                        new
                        {
                            HouseId = 2,
                            Area = 45.0,
                            CreatedAt = new DateTime(2025, 10, 2, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Perfect for students. Compact, fully furnished studio.",
                            LocationId = 2,
                            NumberOfBathrooms = 1,
                            NumberOfRooms = 1,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 3500m,
                            RatingCount = 0,
                            Title = "Cozy Studio near University"
                        },
                        new
                        {
                            HouseId = 3,
                            Area = 450.0,
                            CreatedAt = new DateTime(2025, 10, 3, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "High-end villa facing the sea with private garden.",
                            LocationId = 3,
                            NumberOfBathrooms = 4,
                            NumberOfRooms = 6,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 25000m,
                            RatingCount = 0,
                            Title = "Luxury Sea View Villa"
                        },
                        new
                        {
                            HouseId = 4,
                            Area = 95.0,
                            CreatedAt = new DateTime(2025, 10, 4, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Bright apartment with a large balcony and open kitchen plan.",
                            LocationId = 1,
                            NumberOfBathrooms = 1,
                            NumberOfRooms = 2,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 6000m,
                            RatingCount = 0,
                            Title = "Sunny 2-Bedroom Condo"
                        },
                        new
                        {
                            HouseId = 5,
                            Area = 200.0,
                            CreatedAt = new DateTime(2025, 10, 5, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Top floor penthouse offering panoramic views of the Nile.",
                            LocationId = 1,
                            NumberOfBathrooms = 3,
                            NumberOfRooms = 4,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 12000m,
                            RatingCount = 0,
                            Title = "Nile View Penthouse"
                        },
                        new
                        {
                            HouseId = 6,
                            Area = 110.0,
                            CreatedAt = new DateTime(2025, 10, 6, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Affordable 3-bedroom apartment in a quiet neighborhood.",
                            LocationId = 2,
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 4500m,
                            RatingCount = 0,
                            Title = "Budget Family Home"
                        },
                        new
                        {
                            HouseId = 7,
                            Area = 160.0,
                            CreatedAt = new DateTime(2025, 10, 7, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Charming renovated townhouse with vintage architecture.",
                            LocationId = 1,
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 4,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 8000m,
                            RatingCount = 0,
                            Title = "Historic Townhouse"
                        },
                        new
                        {
                            HouseId = 8,
                            Area = 85.0,
                            CreatedAt = new DateTime(2025, 10, 8, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Serviced apartment designed for business travelers.",
                            LocationId = 1,
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 2,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 9500m,
                            RatingCount = 0,
                            Title = "Executive Suite"
                        },
                        new
                        {
                            HouseId = 9,
                            Area = 140.0,
                            CreatedAt = new DateTime(2025, 10, 9, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Relaxing home away from the city noise, featuring a backyard.",
                            LocationId = 2,
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 5500m,
                            RatingCount = 0,
                            Title = "Suburban Garden House"
                        },
                        new
                        {
                            HouseId = 10,
                            Area = 70.0,
                            CreatedAt = new DateTime(2025, 10, 10, 15, 0, 0, 0, DateTimeKind.Local),
                            Description = "Industrial style loft with high ceilings near the coast.",
                            LocationId = 3,
                            NumberOfBathrooms = 1,
                            NumberOfRooms = 1,
                            OwnerId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            PricePerMonth = 6800m,
                            RatingCount = 0,
                            Title = "Compact Loft"
                        });
                });

            modelBuilder.Entity("Eskon.Domain.Entities.HouseAmenity", b =>
                {
                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("HouseId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("HouseAmenity");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeoLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoLng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LocationId");

                    b.HasIndex("City", "PostalCode");

                    b.HasIndex("City", "Street", "BuildingNumber")
                        .HasDatabaseName("IX_Location_Address");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            BuildingNumber = "15",
                            City = "Cairo",
                            Country = "Egypt",
                            GeoLat = "30.0444",
                            GeoLng = "31.2357",
                            PostalCode = "11511",
                            Street = "Talaat Harb St"
                        },
                        new
                        {
                            LocationId = 2,
                            BuildingNumber = "44",
                            City = "Giza",
                            Country = "Egypt",
                            GeoLat = "30.0131",
                            GeoLng = "31.2089",
                            PostalCode = "12311",
                            Street = "El Tahrir St"
                        },
                        new
                        {
                            LocationId = 3,
                            BuildingNumber = "102",
                            City = "Alexandria",
                            Country = "Egypt",
                            GeoLat = "31.2001",
                            GeoLng = "29.9187",
                            PostalCode = "21500",
                            Street = "Corniche Rd"
                        });
                });

            modelBuilder.Entity("Eskon.Domain.Entities.MediaItem", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("MediaId");

                    b.HasIndex("HouseId");

                    b.HasIndex("HouseId", "IsCover")
                        .IsUnique()
                        .HasFilter("[IsCover] = 1");

                    b.HasIndex("HouseId", "SortOrder");

                    b.ToTable("MediaItem");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "HouseId")
                        .IsUnique();

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.SavedList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "HouseId");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedList");

                    b.HasData(
                        new
                        {
                            UserId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            HouseId = 1,
                            SavedAt = new DateTime(2025, 10, 11, 15, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dd026d4c-abe0-43ef-9ecd-5d99e737bc01",
                            RoleId = "92b75286-d8f8-4061-9995-e6e23ccdee94"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eskon.Domain.Entities.ApplicationUser", b =>
                {
                    b.OwnsMany("Eskon.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.House", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.Location", "Location")
                        .WithMany("Houses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany("OwnedHouses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.HouseAmenity", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.Amenity", "Amenity")
                        .WithMany("HouseAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eskon.Domain.Entities.House", "House")
                        .WithMany("HouseAmenities")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("House");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.House", "House")
                        .WithMany("MediaItems")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.Review", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.House", "House")
                        .WithMany("Reviews")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.SavedList", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.House", "House")
                        .WithMany("SavedBy")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", "User")
                        .WithMany("SavedLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Eskon.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eskon.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("HouseAmenities");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("OwnedHouses");

                    b.Navigation("Reviews");

                    b.Navigation("SavedLists");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.House", b =>
                {
                    b.Navigation("HouseAmenities");

                    b.Navigation("MediaItems");

                    b.Navigation("Reviews");

                    b.Navigation("SavedBy");
                });

            modelBuilder.Entity("Eskon.Domain.Entities.Location", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
